version: '3.7'
services:
  app:
    build: .
    ports:
      - "8090:8090"
  prometheus:
    image: prom/prometheus:v2.20.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
